version: "3"

networks:
  op1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.1.0/24

services:
  nginx:
    build:
      context: ./nginx/
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      op1:
